package com.primeton.dgs.ontology.pojos;

/**
 * TMdComposition generated by MyEclipse Persistence Tools
 * 元数据组合关系
 * @version 1.0 2010-05-04
 */
public class TMdComposition implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String fatherInstanceId;

	private String childInstanceId;

	private String relationship;


	private String fatherClassifierId;

	private String childClassifierId;

	private Long startTime;

	// Constructors

	/** default constructor */
	public TMdComposition()
	{
	}

	public String getFatherClassifierId() {
		return this.fatherClassifierId;
	}

	public void setFatherClassifierId(String fatherClassifierId) {
		this.fatherClassifierId = fatherClassifierId;
	}

	public String getChildClassifierId() {
		return this.childClassifierId;
	}

	public void setChildClassifierId(String childClassifierId) {
		this.childClassifierId = childClassifierId;
	}

	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public String getFatherInstanceId() {
		return fatherInstanceId;
	}

	public void setFatherInstanceId(String fatherInstanceId) {
		this.fatherInstanceId = fatherInstanceId;
	}

	public String getChildInstanceId() {
		return childInstanceId;
	}

	public void setChildInstanceId(String childInstanceId) {
		this.childInstanceId = childInstanceId;
	}

	public String getRelationship() {
		return relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

}