package com.primeton.dgs.ontology.pojos;

/**
 * 元数据表 TMdInstance generated by MyEclipse Persistence Tools
 * 
 * @version 1.0 2010-05-04
 */
public class TMdInstanceSegmentVote implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String segmentId;

	protected String instanceId;

	protected String parentId;

	protected String classifierId;

	protected String segmentWord;

	// Constructors

	/** default constructor */
	public TMdInstanceSegmentVote() {
	}

	/** minimal constructor */
	public TMdInstanceSegmentVote(String instanceId, String classifierId) {
		this.instanceId = instanceId;
		this.classifierId = classifierId;
	}

	public String getSegmentId() {
		return segmentId;
	}

	public void setSegmentId(String segmentId) {
		this.segmentId = segmentId;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	// Property accessors
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public String getClassifierId() {
		return this.classifierId;
	}

	public void setClassifierId(String classifierId) {
		this.classifierId = classifierId;
	}

	public String getSegmentWord() {
		return this.segmentWord;
	}

	public void setSegmentWord(String segmentWord) {
		this.segmentWord = segmentWord;
	}

}