package com.primeton.dgs.ontology.pojos;

/**
 * 元数据表
 * TMdInstance generated by MyEclipse Persistence Tools
 * @version 1.0 2010-05-04
 */
public class TMdInstance implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	protected String instanceId;
	
	protected String parentId;

	protected String instanceCode;

	protected String instanceName;

	protected String classifierId;

	protected String namespace;

	protected String verId;

	protected Long startTime;

	protected String isroot;

	protected String string1;

	protected String string2;

	protected String string3;

	protected String string4;

	protected String string5;

	protected String string6;

	protected String string7;

	protected String string8;

	protected String string9;

	protected String string10;

	protected String string11;

	protected String string12;

	protected String string13;

	protected String string14;

	protected String string15;

	protected String string16;

	protected String string17;

	protected String string18;

	protected String string19;

	protected String string20;

	protected String string21;

	protected String string22;

	protected String string23;

	protected String string24;

	protected String string25;

	protected String string26;

	protected String string27;

	protected String string28;

	protected String string29;

	protected String string30;

	protected String string31;

	protected String string32;

	protected String string33;

	protected String string34;

	protected String string35;

	protected String string36;

	protected String string37;

	protected String string38;

	protected String string39;

	protected String string40;

	protected String string41;

	protected String string42;

	protected String string43;

	protected String string44;

	protected String string45;

	protected String string46;

	protected String string47;

	protected String string48;

	protected String string49;

	protected String string50;

	protected String string51;

	protected String string52;

	protected String string53;

	protected String string54;

	protected String string55;

	protected String string56;

	protected String string57;

	protected String string58;

	protected String string59;

	protected String string60;

	protected String string61;

	protected String string62;

	protected String string63;

	protected String string64;

	protected String string65;

	protected String string66;

	protected String string67;

	protected String string68;

	protected String string69;

	protected String string70;

	protected String string71;

	protected String string72;

	protected String string73;

	protected String string74;

	protected String string75;

	protected String string76;

	protected String string77;

	protected String string78;

	protected String string79;

	protected String string80;

	

	// Constructors

	/** default constructor */
	public TMdInstance()
	{
	}

	/** minimal constructor */
	public TMdInstance(String instanceId, String classifierId)
	{
		this.instanceId = instanceId;
		this.classifierId = classifierId;
	}

	

	// Property accessors
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public String getInstanceCode() {
		return this.instanceCode;
	}

	public void setInstanceCode(String instanceCode) {
		this.instanceCode = instanceCode;
	}

	public String getInstanceName() {
		return this.instanceName;
	}

	public void setInstanceName(String instanceName) {
		this.instanceName = instanceName;
	}

	public String getClassifierId() {
		return this.classifierId;
	}

	public void setClassifierId(String classifierId) {
		this.classifierId = classifierId;
	}

	public String getNamespace() {
		return this.namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public String getVerId() {
		return this.verId;
	}

	public void setVerId(String verId) {
		this.verId = verId;
	}

	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public String getIsroot() {
		return this.isroot;
	}

	public void setIsroot(String isroot) {
		this.isroot = isroot;
	}

	public String getString1() {
		return this.string1;
	}

	public void setString1(String string1) {
		this.string1 = string1;
	}

	public String getString2() {
		return this.string2;
	}

	public void setString2(String string2) {
		this.string2 = string2;
	}

	public String getString3() {
		return this.string3;
	}

	public void setString3(String string3) {
		this.string3 = string3;
	}

	public String getString4() {
		return this.string4;
	}

	public void setString4(String string4) {
		this.string4 = string4;
	}

	public String getString5() {
		return this.string5;
	}

	public void setString5(String string5) {
		this.string5 = string5;
	}

	public String getString6() {
		return this.string6;
	}

	public void setString6(String string6) {
		this.string6 = string6;
	}

	public String getString7() {
		return this.string7;
	}

	public void setString7(String string7) {
		this.string7 = string7;
	}

	public String getString8() {
		return this.string8;
	}

	public void setString8(String string8) {
		this.string8 = string8;
	}

	public String getString9() {
		return this.string9;
	}

	public void setString9(String string9) {
		this.string9 = string9;
	}

	public String getString10() {
		return this.string10;
	}

	public void setString10(String string10) {
		this.string10 = string10;
	}

	public String getString11() {
		return this.string11;
	}

	public void setString11(String string11) {
		this.string11 = string11;
	}

	public String getString12() {
		return this.string12;
	}

	public void setString12(String string12) {
		this.string12 = string12;
	}

	public String getString13() {
		return this.string13;
	}

	public void setString13(String string13) {
		this.string13 = string13;
	}

	public String getString14() {
		return this.string14;
	}

	public void setString14(String string14) {
		this.string14 = string14;
	}

	public String getString15() {
		return this.string15;
	}

	public void setString15(String string15) {
		this.string15 = string15;
	}

	public String getString16() {
		return this.string16;
	}

	public void setString16(String string16) {
		this.string16 = string16;
	}

	public String getString17() {
		return this.string17;
	}

	public void setString17(String string17) {
		this.string17 = string17;
	}

	public String getString18() {
		return this.string18;
	}

	public void setString18(String string18) {
		this.string18 = string18;
	}

	public String getString19() {
		return this.string19;
	}

	public void setString19(String string19) {
		this.string19 = string19;
	}

	public String getString20() {
		return this.string20;
	}

	public void setString20(String string20) {
		this.string20 = string20;
	}

	public String getString21() {
		return this.string21;
	}

	public void setString21(String string21) {
		this.string21 = string21;
	}

	public String getString22() {
		return this.string22;
	}

	public void setString22(String string22) {
		this.string22 = string22;
	}

	public String getString23() {
		return this.string23;
	}

	public void setString23(String string23) {
		this.string23 = string23;
	}

	public String getString24() {
		return this.string24;
	}

	public void setString24(String string24) {
		this.string24 = string24;
	}

	public String getString25() {
		return this.string25;
	}

	public void setString25(String string25) {
		this.string25 = string25;
	}

	public String getString26() {
		return this.string26;
	}

	public void setString26(String string26) {
		this.string26 = string26;
	}

	public String getString27() {
		return this.string27;
	}

	public void setString27(String string27) {
		this.string27 = string27;
	}

	public String getString28() {
		return this.string28;
	}

	public void setString28(String string28) {
		this.string28 = string28;
	}

	public String getString29() {
		return this.string29;
	}

	public void setString29(String string29) {
		this.string29 = string29;
	}

	public String getString30() {
		return this.string30;
	}

	public void setString30(String string30) {
		this.string30 = string30;
	}

	public String getString31() {
		return this.string31;
	}

	public void setString31(String string31) {
		this.string31 = string31;
	}

	public String getString32() {
		return this.string32;
	}

	public void setString32(String string32) {
		this.string32 = string32;
	}

	public String getString33() {
		return this.string33;
	}

	public void setString33(String string33) {
		this.string33 = string33;
	}

	public String getString34() {
		return this.string34;
	}

	public void setString34(String string34) {
		this.string34 = string34;
	}

	public String getString35() {
		return this.string35;
	}

	public void setString35(String string35) {
		this.string35 = string35;
	}

	public String getString36() {
		return this.string36;
	}

	public void setString36(String string36) {
		this.string36 = string36;
	}

	public String getString37() {
		return this.string37;
	}

	public void setString37(String string37) {
		this.string37 = string37;
	}

	public String getString38() {
		return this.string38;
	}

	public void setString38(String string38) {
		this.string38 = string38;
	}

	public String getString39() {
		return this.string39;
	}

	public void setString39(String string39) {
		this.string39 = string39;
	}

	public String getString40() {
		return this.string40;
	}

	public void setString40(String string40) {
		this.string40 = string40;
	}

	public String getString41() {
		return this.string41;
	}

	public void setString41(String string41) {
		this.string41 = string41;
	}

	public String getString42() {
		return this.string42;
	}

	public void setString42(String string42) {
		this.string42 = string42;
	}

	public String getString43() {
		return this.string43;
	}

	public void setString43(String string43) {
		this.string43 = string43;
	}

	public String getString44() {
		return this.string44;
	}

	public void setString44(String string44) {
		this.string44 = string44;
	}

	public String getString45() {
		return this.string45;
	}

	public void setString45(String string45) {
		this.string45 = string45;
	}

	public String getString46() {
		return this.string46;
	}

	public void setString46(String string46) {
		this.string46 = string46;
	}

	public String getString47() {
		return this.string47;
	}

	public void setString47(String string47) {
		this.string47 = string47;
	}

	public String getString48() {
		return this.string48;
	}

	public void setString48(String string48) {
		this.string48 = string48;
	}

	public String getString49() {
		return this.string49;
	}

	public void setString49(String string49) {
		this.string49 = string49;
	}

	public String getString50() {
		return this.string50;
	}

	public void setString50(String string50) {
		this.string50 = string50;
	}

	public String getString51() {
		return this.string51;
	}

	public void setString51(String string51) {
		this.string51 = string51;
	}

	public String getString52() {
		return this.string52;
	}

	public void setString52(String string52) {
		this.string52 = string52;
	}

	public String getString53() {
		return this.string53;
	}

	public void setString53(String string53) {
		this.string53 = string53;
	}

	public String getString54() {
		return this.string54;
	}

	public void setString54(String string54) {
		this.string54 = string54;
	}

	public String getString55() {
		return this.string55;
	}

	public void setString55(String string55) {
		this.string55 = string55;
	}

	public String getString56() {
		return this.string56;
	}

	public void setString56(String string56) {
		this.string56 = string56;
	}

	public String getString57() {
		return this.string57;
	}

	public void setString57(String string57) {
		this.string57 = string57;
	}

	public String getString58() {
		return this.string58;
	}

	public void setString58(String string58) {
		this.string58 = string58;
	}

	public String getString59() {
		return this.string59;
	}

	public void setString59(String string59) {
		this.string59 = string59;
	}

	public String getString60() {
		return this.string60;
	}

	public void setString60(String string60) {
		this.string60 = string60;
	}

	public String getString61() {
		return this.string61;
	}

	public void setString61(String string61) {
		this.string61 = string61;
	}

	public String getString62() {
		return this.string62;
	}

	public void setString62(String string62) {
		this.string62 = string62;
	}

	public String getString63() {
		return this.string63;
	}

	public void setString63(String string63) {
		this.string63 = string63;
	}

	public String getString64() {
		return this.string64;
	}

	public void setString64(String string64) {
		this.string64 = string64;
	}

	public String getString65() {
		return this.string65;
	}

	public void setString65(String string65) {
		this.string65 = string65;
	}

	public String getString66() {
		return this.string66;
	}

	public void setString66(String string66) {
		this.string66 = string66;
	}

	public String getString67() {
		return this.string67;
	}

	public void setString67(String string67) {
		this.string67 = string67;
	}

	public String getString68() {
		return this.string68;
	}

	public void setString68(String string68) {
		this.string68 = string68;
	}

	public String getString69() {
		return this.string69;
	}

	public void setString69(String string69) {
		this.string69 = string69;
	}

	public String getString70() {
		return this.string70;
	}

	public void setString70(String string70) {
		this.string70 = string70;
	}

	public String getString71() {
		return this.string71;
	}

	public void setString71(String string71) {
		this.string71 = string71;
	}

	public String getString72() {
		return this.string72;
	}

	public void setString72(String string72) {
		this.string72 = string72;
	}

	public String getString73() {
		return this.string73;
	}

	public void setString73(String string73) {
		this.string73 = string73;
	}

	public String getString74() {
		return this.string74;
	}

	public void setString74(String string74) {
		this.string74 = string74;
	}

	public String getString75() {
		return this.string75;
	}

	public void setString75(String string75) {
		this.string75 = string75;
	}

	public String getString76() {
		return this.string76;
	}

	public void setString76(String string76) {
		this.string76 = string76;
	}

	public String getString77() {
		return this.string77;
	}

	public void setString77(String string77) {
		this.string77 = string77;
	}

	public String getString78() {
		return this.string78;
	}

	public void setString78(String string78) {
		this.string78 = string78;
	}

	public String getString79() {
		return this.string79;
	}

	public void setString79(String string79) {
		this.string79 = string79;
	}

	public String getString80() {
		return this.string80;
	}

	public void setString80(String string80) {
		this.string80 = string80;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

}