package com.primeton.dgs.ontology.pojos;

/**
 * 元数据表
 * TMdInstance generated by MyEclipse Persistence Tools
 * @version 1.0 2010-05-04
 */
public class TMdInstanceSegment implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	protected String instanceId;
	
	protected String parentId;

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	protected String instanceCode;

	protected String instanceName;

	protected String classifierId;

	protected String namespace;

	protected String segmentWord;
	
	
	public String getNature() {
		return nature;
	}

	
	public void setNature(String nature) {
		this.nature = nature;
	}

	
	public String getChinese() {
		return chinese;
	}

	
	public void setChinese(String chinese) {
		this.chinese = chinese;
	}

	protected String tablename;
	
	protected String nature;
	
	protected String chinese;
	
	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getTablecode() {
		return tablecode;
	}

	public void setTablecode(String tablecode) {
		this.tablecode = tablecode;
	}

	protected String tablecode;


	// Constructors

	/** default constructor */
	public TMdInstanceSegment()
	{
	}

	/** minimal constructor */
	public TMdInstanceSegment(String instanceId, String classifierId)
	{
		this.instanceId = instanceId;
		this.classifierId = classifierId;
	}

	

	// Property accessors
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public String getInstanceCode() {
		return this.instanceCode;
	}

	public void setInstanceCode(String instanceCode) {
		this.instanceCode = instanceCode;
	}

	public String getInstanceName() {
		return this.instanceName;
	}

	public void setInstanceName(String instanceName) {
		this.instanceName = instanceName;
	}

	public String getClassifierId() {
		return this.classifierId;
	}

	public void setClassifierId(String classifierId) {
		this.classifierId = classifierId;
	}

	public String getNamespace() {
		return this.namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public String getSegmentWord() {
		return this.segmentWord;
	}

	public void setSegmentWord(String segmentWord) {
		this.segmentWord = segmentWord;
	}

}