package com.primeton.dgs.ontology.pojos;

/**
 * 元数据表 TMdInstance generated by MyEclipse Persistence Tools
 * 
 * @version 1.0 2010-05-04
 */
public class TSegmentRealation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

		
	protected String segmentFrom;

	protected String segmentTo;

	protected String type;

	// Constructors

	
	public String getSegmentFrom() {
		return segmentFrom;
	}

	
	public void setSegmentFrom(String segmentFrom) {
		this.segmentFrom = segmentFrom;
	}

	
	public String getSegmentTo() {
		return segmentTo;
	}

	
	public void setSegmentTo(String segmentTo) {
		this.segmentTo = segmentTo;
	}

	
	public String getType() {
		return type;
	}

	
	public void setType(String type) {
		this.type = type;
	}

	/** default constructor */
	public TSegmentRealation() {
	}



}